#!/bin/bash

# GitHub Daily Trends Cron Job
# 每天晚上9点执行

# 加载环境变量
source "$HOME/.local/bin/env"

# 进入工作目录
cd "$HOME/workspace/github-daily-trends" || exit 1

# 获取今天的日期
TODAY=$(date +%Y-%m-%d)
MONTH=$(date +%Y-%m)
MONTH_DIR="$HOME/workspace/github-daily-trends/$MONTH"

# 创建月份目录
mkdir -p "$MONTH_DIR"

# 获取GitHub趋势（最近一天创建，按stars排序）
YESTERDAY=$(date -v-1d +%Y-%m-%d)
gh api "search/repositories?q=created:%3E$YESTERDAY&sort=stars&order=desc&per_page=10" --jq '.items | map({name: .full_name, description: .description, stars: .stargazers_count, language: .language, url: .html_url})' > /tmp/trends_$TODAY.json 2>/tmp/gh_error.log

# 生成Markdown报告
cat > "$MONTH_DIR/$TODAY.md" << 'EOF'
# GitHub Daily Trends - $TODAY

> Generated by 小狸 🐱

## 📈 Today's Hot Repositories

EOF

# 解析JSON并添加到报告
if [ -s /tmp/trends_$TODAY.json ]; then
    echo "" >> "$MONTH_DIR/$TODAY.md"
    # 使用简单的jq语法，确保兼容
    jq -r '.[] | "- [" + .name + "](" + .url + ") ⭐ " + (.stars | tostring) + " - " + (.description // "无描述")' /tmp/trends_$TODAY.json >> "$MONTH_DIR/$TODAY.md" 2>>/tmp/jq_error.log || echo "jq解析出错" >> "$MONTH_DIR/$TODAY.md"
    echo "" >> "$MONTH_DIR/$TODAY.md"
    echo "生成完成 ✅" >> "$MONTH_DIR/$TODAY.md"
else
    echo "" >> "$MONTH_DIR/$TODAY.md"
    echo "⚠️ 获取趋势数据失败或数据为空" >> "$MONTH_DIR/$TODAY.md"
    echo "" >> "$MONTH_DIR/$TODAY.md"
    echo "错误日志：" >> "$MONTH_DIR/$TODAY.md"
    cat /tmp/gh_error.log >> "$MONTH_DIR/$TODAY.md" 2>/dev/null || true
fi

# Git提交和推送
git add .
git commit -m "Add GitHub trends $TODAY" --allow-empty
git push

# 清理
rm -f /tmp/trends_$TODAY.json /tmp/gh_error.log /tmp/jq_error.log
