#!/bin/bash

# GitHub Daily Trends - 通过抓取 GitHub Trending 页面
# 每天晚上9点执行

# 加载环境变量
source "$HOME/.local/bin/env"

# 基于脚本位置定位仓库，避免目录迁移后路径失效
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 进入工作目录
cd "$SCRIPT_DIR" || exit 1

# 获取今天的日期
TODAY=$(date +%Y-%m-%d)
MONTH=$(date +%Y-%m)
MONTH_DIR="$SCRIPT_DIR/$MONTH"

# 创建月份目录
mkdir -p "$MONTH_DIR"

# 抓取 GitHub Trending 页面到临时文件
curl -sL "https://github.com/trending" \
    -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36" \
    -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
    -H "Accept-Language: en-US,en;q=0.5" \
    --compressed 2>/dev/null > /tmp/trending_raw.html

# 生成Markdown报告
cat > "$MONTH_DIR/$TODAY.md" << EOF
# GitHub Daily Trends - $TODAY

> Generated by 小狸 🐱 | Data from [GitHub Trending](https://github.com/trending)

## 🔥 Today's Trending Repositories

EOF

# 解析仓库信息并追加到文件
python3 << 'PYEOF' >> "$MONTH_DIR/$TODAY.md" 2>>/tmp/python_error.log
import re

with open('/tmp/trending_raw.html', 'r', encoding='utf-8') as f:
    html = f.read()

# 匹配每个 article 块
pattern = r'<article[^>]*class="Box-row"(.*?)</article>'
articles = re.findall(pattern, html, re.DOTALL)

repos = []
for article in articles:
    # 提取仓库名
    repo_match = re.search(r'href="/([^/]+/[^"]+)"[^>]*class="Link"', article)
    if not repo_match:
        continue
    repo = repo_match.group(1)
    
    # 跳过非仓库链接
    if any(x in repo for x in ['login', 'sponsors/', 'topics/', 'explore/', 'collections/', 'events/']):
        continue
    
    # 提取描述
    desc_match = re.search(r'<p[^>]*class="col[^"]*color-fg-muted[^"]*"[^>]*>(.*?)\s*</p>', article, re.DOTALL)
    desc = ''
    if desc_match:
        desc = re.sub(r'<[^>]+>', '', desc_match.group(1))
        desc = desc.strip()
    
    # 提取语言
    lang_match = re.search(r'"programmingLanguage":"([^"]+)"', article)
    lang = lang_match.group(1) if lang_match else ''
    
    # 提取今日 star 数
    stars_match = re.search(r'(\d+)\s+stars?\s+today', article, re.IGNORECASE)
    stars_today = stars_match.group(1) if stars_match else ''
    
    repos.append({
        'name': repo,
        'desc': desc,
        'lang': lang,
        'stars_today': stars_today
    })

# 去重
seen = set()
unique_repos = []
for r in repos:
    if r['name'] not in seen:
        seen.add(r['name'])
        unique_repos.append(r)

# 输出
for i, r in enumerate(unique_repos[:25], 1):
    print(f"### {i}. [{r['name']}](https://github.com/{r['name']})")
    
    info_parts = []
    if r['lang']:
        info_parts.append(f"📝 {r['lang']}")
    if r['stars_today']:
        info_parts.append(f"⭐ +{r['stars_today']} today")
    
    if info_parts:
        print(f"\n{' | '.join(info_parts)}")
    
    if r['desc']:
        print(f"\n{r['desc']}")
    
    print()

PYEOF

# 检查是否有内容，如果没有使用备用方案
LINE_COUNT=$(wc -l < "$MONTH_DIR/$TODAY.md")
if [ "$LINE_COUNT" -lt 10 ]; then
    echo "" >> "$MONTH_DIR/$TODAY.md"
    echo "## 📊 Trending Repositories (Backup List)" >> "$MONTH_DIR/$TODAY.md"
    echo "" >> "$MONTH_DIR/$TODAY.md"
    
    grep -oE 'href="/[^/]+/[^"]+" data-view-component="true" class="Link"' /tmp/trending_raw.html | \
        sed 's/href="//;s/" data-view-component.*$//' | \
        grep -vE '^/(login|sponsors|topics|explore|collections|events)' | \
        awk '!seen[$0]++' | \
        while read repo; do
            echo "- [$repo](https://github.com$repo)"
        done | head -25 >> "$MONTH_DIR/$TODAY.md"
fi

echo "" >> "$MONTH_DIR/$TODAY.md"
echo "---" >> "$MONTH_DIR/$TODAY.md"
echo "" >> "$MONTH_DIR/$TODAY.md"
echo "✅ 生成于 $(date '+%Y-%m-%d %H:%M:%S')" >> "$MONTH_DIR/$TODAY.md"

# Git提交和推送
git add .
git commit -m "Add GitHub trends $TODAY" --allow-empty
git push

# 清理
rm -f /tmp/trending_raw.html /tmp/python_error.log
