#!/bin/bash

# GitHub Daily Trends Cron Job
# 每天晚上9点执行

# 加载环境变量
source "$HOME/.local/bin/env"

# 进入工作目录
cd "$HOME/workspace/github-daily-trends" || exit 1

# 获取今天的日期
TODAY=$(date +%Y-%m-%d)
MONTH=$(date +%Y-%m)
MONTH_DIR="$HOME/workspace/github-daily-trends/$MONTH"

# 创建月份目录
mkdir -p "$MONTH_DIR"

# 获取GitHub趋势（今日创建，按stars排序）
gh api "search/repositories?q=created:>$(( $(date -v-1d +%Y-%m-%d) ))&sort=stars&per_page=15" --jq '.items[:15] | .[] | {name: .full_name, description: .description, stars: .stargazers_count, language: .language, url: .html_url}' > /tmp/trends_$TODAY.json 2>/dev/null

# 生成Markdown报告
cat > "$MONTH_DIR/$TODAY.md" << EOF
# GitHub Daily Trends - $TODAY

> Generated by 小狸 🐱

## 📈 Today's Hot Repositories

EOF

# 解析JSON并添加到报告
jq -r '.[] | "| \(\.name) | \(\.stars) | \(.language // "-") | \(.description // "-") |"' /tmp/trends_$TODAY.md 2>/dev/null || true

# Git提交和推送
git add .
git commit -m "Add GitHub trends $TODAY" --allow-empty
git push

# 清理
rm -f /tmp/trends_$TODAY.json
